"use strict";
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("olympus", {
  checkEnv: () => ipcRenderer.invoke("env:check"),
  // Pegasus
  pegasusStatus: () => ipcRenderer.invoke("pegasus:status"),
  installPegasus: (code) => ipcRenderer.invoke("pegasus:install", code),
  // Zevs
  zevsStatus: () => ipcRenderer.invoke("zevs:status"),
  installZevs: () => ipcRenderer.invoke("zevs:install"),
  openZevs: () => ipcRenderer.invoke("zevs:open"),
  onZevsProgress: (cb) => ipcRenderer.on("zevs:progress", (_e, d) => cb(d)),
  // Titan (dev — super admin)
  titanStatus: () => ipcRenderer.invoke("titan:status"),
  pickTitanFolder: () => ipcRenderer.invoke("titan:pickFolder"),
  installTitan: () => ipcRenderer.invoke("titan:install"),
  openTitan: () => ipcRenderer.invoke("titan:open"),
  onTitanProgress: (cb) => ipcRenderer.on("titan:progress", (_e, d) => cb(d)),
  // Auth + membres
  authSession: () => ipcRenderer.invoke("auth:session"),
  authLogin: (email, password) => ipcRenderer.invoke("auth:login", email, password),
  authSetPassword: (pw) => ipcRenderer.invoke("auth:setPassword", pw),
  authLogout: () => ipcRenderer.invoke("auth:logout"),
  authNeedsBootstrap: () => ipcRenderer.invoke("auth:needsBootstrap"),
  authBootstrap: (d) => ipcRenderer.invoke("auth:bootstrap", d),
  membersList: () => ipcRenderer.invoke("members:list"),
  membersCreate: (d) => ipcRenderer.invoke("members:create", d),
  membersDelete: (id) => ipcRenderer.invoke("members:delete", id),
  membersResetPassword: (id) => ipcRenderer.invoke("members:resetPassword", id),
  membersSetRole: (id, role) => ipcRenderer.invoke("members:setRole", id, role),
  // Hermès (chat)
  chatList: (afterId) => ipcRenderer.invoke("chat:list", afterId),
  chatSend: (body) => ipcRenderer.invoke("chat:send", body),
  // Chronos (calendrier)
  chronosList: (from, to) => ipcRenderer.invoke("chronos:list", from, to),
  chronosCreate: (ev) => ipcRenderer.invoke("chronos:create", ev),
  chronosUpdate: (id, patch) => ipcRenderer.invoke("chronos:update", id, patch),
  chronosDelete: (id) => ipcRenderer.invoke("chronos:delete", id),
  // Présence
  presenceBeat: () => ipcRenderer.invoke("presence:beat"),
  presenceOnline: () => ipcRenderer.invoke("presence:online"),
  // Iris (email + CRM)
  irisStatus: () => ipcRenderer.invoke("iris:status"),
  irisConnect: (email, pass) => ipcRenderer.invoke("iris:connect", email, pass),
  irisDisconnect: () => ipcRenderer.invoke("iris:disconnect"),
  irisSend: (d) => ipcRenderer.invoke("iris:send", d),
  irisLabels: () => ipcRenderer.invoke("iris:labels"),
  irisCreateLabel: (name) => ipcRenderer.invoke("iris:createLabel", name),
  crmEmails: () => ipcRenderer.invoke("crm:emails"),
  crmContacts: () => ipcRenderer.invoke("crm:contacts"),
  // Contrôle par Claude Code (MCP)
  claudeStatus: () => ipcRenderer.invoke("claude:status"),
  claudeInstall: () => ipcRenderer.invoke("claude:install"),
  // Medusa (MCP Pegasus)
  medusaStatus: () => ipcRenderer.invoke("medusa:status"),
  medusaInstall: () => ipcRenderer.invoke("medusa:install"),
  medusaDiag: () => ipcRenderer.invoke("medusa:diag"),
  // Pegasus — clients connectés
  pegasusClients: () => ipcRenderer.invoke("pegasus:clients"),
  // Pegasus — le parc + la bibliothèque Orphic
  pegasusSites: () => ipcRenderer.invoke("pegasus:sites"),
  pegasusSiteHealth: (key) => ipcRenderer.invoke("pegasus:siteHealth", key),
  pegasusSiteInspect: (key) => ipcRenderer.invoke("pegasus:siteInspect", key),
  pegasusSiteDiag: (key) => ipcRenderer.invoke("pegasus:siteDiag", key),
  pegasusMetricsGet: (key) => ipcRenderer.invoke("pegasus:metricsGet", key),
  pegasusMetricsAppend: (key, kind, point) => ipcRenderer.invoke("pegasus:metricsAppend", key, kind, point),
  pegasusExportPdf: (html, filename) => ipcRenderer.invoke("pegasus:exportPdf", html, filename),
  pegasusAnalyticsStatus: () => ipcRenderer.invoke("pegasus:analyticsStatus"),
  pegasusAudiencePegasus: (key, days) => ipcRenderer.invoke("pegasus:audiencePegasus", key, days),
  pegasusAudienceReset: (key) => ipcRenderer.invoke("pegasus:audienceReset", key),
  pegasusReportsList: (key) => ipcRenderer.invoke("pegasus:reportsList", key),
  pegasusReportsSetup: () => ipcRenderer.invoke("pegasus:reportsSetup"),
  pegasusReportRunNow: (key) => ipcRenderer.invoke("pegasus:reportRunNow", key),
  pegasusGoogleConnect: () => ipcRenderer.invoke("pegasus:googleConnect"),
  pegasusGoogleDisconnect: () => ipcRenderer.invoke("pegasus:googleDisconnect"),
  pegasusAnalyticsConfigGet: (key) => ipcRenderer.invoke("pegasus:analyticsConfigGet", key),
  pegasusAnalyticsConfigSet: (key, cfg) => ipcRenderer.invoke("pegasus:analyticsConfigSet", key, cfg),
  pegasusAnalyticsFetch: (key, days) => ipcRenderer.invoke("pegasus:analyticsFetch", key, days),
  pegasusSiteSeo: (key, limit) => ipcRenderer.invoke("pegasus:siteSeo", key, limit),
  pegasusSiteContent: (key) => ipcRenderer.invoke("pegasus:siteContent", key),
  pegasusArboGet: (key) => ipcRenderer.invoke("pegasus:arboGet", key),
  pegasusArboScan: (key, homeWp) => ipcRenderer.invoke("pegasus:arboScan", key, homeWp),
  pegasusArboSave: (key, arbo) => ipcRenderer.invoke("pegasus:arboSave", key, arbo),
  pegasusMoodboardGet: (key) => ipcRenderer.invoke("pegasus:moodboardGet", key),
  pegasusMoodboardSave: (key, mb) => ipcRenderer.invoke("pegasus:moodboardSave", key, mb),
  pegasusMoodboardScan: (key) => ipcRenderer.invoke("pegasus:moodboardScan", key),
  pegasusPageSections: (url) => ipcRenderer.invoke("pegasus:pageSections", url),
  pegasusMbList: (key) => ipcRenderer.invoke("pegasus:mbList", key),
  pegasusMbSave: (key, mb, label, deployAsCurrent) => ipcRenderer.invoke("pegasus:mbSave", key, mb, label, deployAsCurrent),
  pegasusMbLoad: (key, id) => ipcRenderer.invoke("pegasus:mbLoad", key, id),
  pegasusMbRename: (key, id, label) => ipcRenderer.invoke("pegasus:mbRename", key, id, label),
  pegasusMbDelete: (key, id) => ipcRenderer.invoke("pegasus:mbDelete", key, id),
  pegasusPipelineGet: (key) => ipcRenderer.invoke("pegasus:pipelineGet", key),
  pegasusPipelineSave: (key, pl) => ipcRenderer.invoke("pegasus:pipelineSave", key, pl),
  pegasusPipelineDiscuss: (key, prompt) => ipcRenderer.invoke("pegasus:pipelineDiscuss", key, prompt),
  pegasusPrjList: (key) => ipcRenderer.invoke("pegasus:prjList", key),
  pegasusPrjSave: (key, pl, label) => ipcRenderer.invoke("pegasus:prjSave", key, pl, label),
  pegasusPrjLoad: (key, id) => ipcRenderer.invoke("pegasus:prjLoad", key, id),
  pegasusPrjRename: (key, id, label) => ipcRenderer.invoke("pegasus:prjRename", key, id, label),
  pegasusPrjDelete: (key, id) => ipcRenderer.invoke("pegasus:prjDelete", key, id),
  pegasusWireList: (key) => ipcRenderer.invoke("pegasus:wireList", key),
  pegasusWireSave: (key, arbo, label, deployAsCurrent) => ipcRenderer.invoke("pegasus:wireSave", key, arbo, label, deployAsCurrent),
  pegasusWireLoad: (key, id) => ipcRenderer.invoke("pegasus:wireLoad", key, id),
  pegasusWireRename: (key, id, label) => ipcRenderer.invoke("pegasus:wireRename", key, id, label),
  pegasusWireDelete: (key, id) => ipcRenderer.invoke("pegasus:wireDelete", key, id),
  pegasusWireWork: (key, id, mode, moodId) => ipcRenderer.invoke("pegasus:wireWork", key, id, mode, moodId),
  pegasusSitePerf: (key, strategy) => ipcRenderer.invoke("pegasus:sitePerf", key, strategy),
  pegasusRefs: (filters) => ipcRenderer.invoke("pegasus:refs", filters),
  pegasusRefAdd: (row) => ipcRenderer.invoke("pegasus:refAdd", row),
  pegasusRefSet: (id, statut) => ipcRenderer.invoke("pegasus:refSet", id, statut),
  pegasusRefDelete: (id) => ipcRenderer.invoke("pegasus:refDelete", id),
  pegasusRefsSetup: () => ipcRenderer.invoke("pegasus:refsSetup"),
  pegasusRevealPlugin: () => ipcRenderer.invoke("pegasus:revealPlugin"),
  pegasusWorkspace: () => ipcRenderer.invoke("pegasus:workspace"),
  pegasusRevealFolder: (slug) => ipcRenderer.invoke("pegasus:revealFolder", slug),
  pegasusFolderExists: (slug) => ipcRenderer.invoke("pegasus:folderExists", slug),
  pegasusScaffold: (project) => ipcRenderer.invoke("pegasus:scaffold", project),
  pegasusCopySite: (key, mode) => ipcRenderer.invoke("pegasus:copySite", key, mode),
  pegasusBackup: (key, kind, note) => ipcRenderer.invoke("pegasus:backup", key, kind, note),
  pegasusBackups: (key) => ipcRenderer.invoke("pegasus:backups", key),
  pegasusRestore: (key, backupId) => ipcRenderer.invoke("pegasus:restore", key, backupId),
  pegasusBackupsSetup: () => ipcRenderer.invoke("pegasus:backupsSetup"),
  pegasusPushInfo: (key) => ipcRenderer.invoke("pegasus:pushInfo", key),
  pegasusPush: (key) => ipcRenderer.invoke("pegasus:push", key),
  pegasusWorkOn: (key, prompt) => ipcRenderer.invoke("pegasus:workOn", key, prompt),
  // Éole — transfert de fichiers
  eoleStatus: () => ipcRenderer.invoke("eole:status"),
  eoleSetupSql: () => ipcRenderer.invoke("eole:setupSql"),
  eolePick: () => ipcRenderer.invoke("eole:pick"),
  eoleSend: (payload) => ipcRenderer.invoke("eole:send", payload),
  eoleList: () => ipcRenderer.invoke("eole:list"),
  eoleDelete: (id, objectPath) => ipcRenderer.invoke("eole:delete", id, objectPath),
  // Chronos — upload moodboard / références
  chronosUpload: (folder) => ipcRenderer.invoke("chronos:upload", folder),
  // Divers
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
});
